version: '3'

services:
  api:
    container_name: nlp_hate_identify_api
    build:
      context: ./
      dockerfile: Dockerfile
    #command: tail -f /dev/null
    command: bash -c "python -m nltk.downloader punkt && python app.py"
    working_dir: /app
    ports:
      - "6543:6543"
    volumes:
      - ./:/app

