version: '3'

services:
  api:
    container_name: nlp_hate_identify_api
    build:
      context: ./
      dockerfile: Dockerfile
    #command: python app.py
    command: tail -f /dev/null
    working_dir: /app
    ports:
      - "6543:6543"
    volumes:
      - ./:/app

